// Renders students × nodes grid from state.json (generated by scripts/harvest.py).
"use strict";

const ICON = { accepted: "🟢", "changes-requested": "🔴", open: "🟡" };
const TITLE = {
  accepted: "принято",
  "changes-requested": "запрошены изменения",
  open: "на проверке",
};

async function main() {
  const res = await fetch("state.json");
  const state = await res.json();
  const app = document.getElementById("app");

  document.getElementById("meta").textContent =
    `Обновлено: ${state.generated} · группа ${[...new Set(state.students.map(s => s.group))].join(", ")}`;

  document.getElementById("legend").innerHTML =
    Object.entries(ICON).map(([k, v]) => `<span>${v} ${TITLE[k]}</span>`).join("")
    + `<span>⚪ не сдано</span>`;

  const nodes = state.nodes.filter(n => n.kind === "milestone");
  const grid = state.grid || {};
  const byHandle = Object.fromEntries(state.students.map(s => [s.handle.toLowerCase(), s]));

  let html = "<table><tr><th>Студент</th>";
  for (const n of nodes) html += `<th class="node" title="${esc(n.title)}">${esc(n.id)}</th>`;
  html += "<th>Баллы</th><th>Ветка</th></tr>";

  for (const s of state.students) {
    const h = s.handle.toLowerCase();
    const cells = grid[h] || {};
    html += `<tr><td>${esc(s.name)} <a href="${esc(s.fork)}">(${esc(s.handle)})</a></td>`;
    for (const n of nodes) {
      const c = cells[n.id];
      if (!c) { html += `<td class="st" title="не сдано">⚪</td>`; continue; }
      const icon = ICON[c.state] || "⚪";
      const tip = c.via ? `${TITLE[c.state]} (via ${c.via})` : (TITLE[c.state] || c.state);
      const links = [];
      if (c.issue) links.push(`<a href="https://github.com/${state.repo}/issues/${c.issue}">issue</a>`);
      if (c.pr_url) links.push(`<a href="${esc(c.pr_url)}">PR</a>`);
      html += `<td class="st" title="${esc(tip)}">${icon}<br>${links.join(" · ")}</td>`;
    }
    const pts = Object.entries(cells)
      .filter(([nid]) => state.nodes.find(n => n.id === nid)?.kind === "achievement")
      .reduce((sum, [nid, c]) => sum + (c.state === "accepted"
        ? (state.nodes.find(n => n.id === nid)?.points || 0) : 0), 0);
    html += `<td class="points">${pts || ""}</td>`;
    html += `<td><a href="${esc(s.fork)}/pulls">PRs</a></td></tr>`;
  }
  html += "</table>";
  app.innerHTML = html;
}

function esc(x) {
  return String(x).replace(/[&<>"']/g, c =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

main().catch(e => { document.getElementById("app").textContent = "Ошибка: " + e; });
